# client -> server message codes
CS_PONG = 1
CS_TEXTMESSAGE = 15
CS_SELECTCHARACTER = 56
CS_CHATCLIENTLOGIN = 79

MSG_ERROR = 1
MSG_GLOBAL_LOGIN_MSG = 13
MSG_USER_CHATCLIENTONLY = 15
MSG_USER_GALAXY = 4
MSG_USER_GLOBAL = 3
MSG_USER_GROUP = 11
MSG_USER_HELP = 14
MSG_USER_MODERATOR = 12
MSG_USER_TEAM = 5
MSG_USER_TRADE = 10
MSG_USER_USER = 7
MSG_USER_LFG = 17

# server -> client message codes
SC_PING = 1
SC_HELLO = 2
SC_TEXTMESSAGE = 16
SC_TEAM = 38
SC_TEAMMEMBER = 40
SC_LOGINFAIL = 58
SC_CHARACTERLIST = 64
SC_DISCONNECT = 67
SC_UPDATECLIENT = 68

USER_TALK_GLOBAL = 0
USER_TALK_GALAXY = 1
USER_TALK_TEAM = 2
USER_TALK_INDIVIDUAL = 3
USER_TALK_TRADE = 4
USER_TALK_GROUP = 6
USER_TALK_MODERATOR = 7
USER_TALK_HELP = 8
USER_TALK_CHATCLIENTONLY = 9

